### ISSUE TITLE
Working with entities that have more than 8 components

### ISSUE THREAD

**Issue by ImVexed** [mlange-42/arche#307]
Hello!

I'm finding as I add more and more complexity to my ECS that I'm frequently adding Entities that have more than 8 components. And it can feel strange to have `compMapper1` `compMapper2`, etc...

I know there's nothing stopping me from just chaining `generic.NewMap`'s together. But is there anything that lets me group components into bundles kind of like how bevy does it? Or should I just add them all to an exchange or something?

**Comment by mlange-42** [comment]
Firstly, I restricted myself to 8 components as long as there are no use cases that require more. I can extend it to e.g. 12 components, but that would still be limited.

Component bundles would be a nice feature, but given Go's limitations, I am not sure how they could be combined with generics when it goes beyond constructing the bundles (e.g. getting the just-created components with the correct type).

What I would suggest is to use the ID-based API here. Create an array of component IDs using generics (with `ecs.ComponentID[Comp](world)`), and pass the array to `World.NewEntity`. You should create the array at initialization / outside your entity creation loop, of course, just like with setting up the mapper. So kind of, your array of IDs is the component bundle then.

**Comment by ImVexed** [comment]
Thanks, that makes sense. 

What are your thoughts on the 128-component limit? It's pretty likely I'll need more than 128 for the complexity of the system's I'm creating. Is there much I can do outside of starting to bundle components?

**Comment by mlange-42** [comment]
The restriction to a maximum of 128 components is mainly a performance considerations, as it allows to completely avoid maps and only use bitmasks and array indexing. Also, for the main purpose of building simulation models, a very high number of components is unlikely.

With some performance degradation, it might be possible to switch to some `BitSet` implemenation for unlimited bits. Not sure about the places where fixed-size arrays/slices are used. Particularly whether it would then be necessary to register all components at startup instead of being able to create them dynamically, which I would not like. Another option could be to just specify the maximum number of components at startup in case they are expected to exceed 128.

What Flecs does is to use bitmasks and array indexing for the first 128 components, and maps for those beyond.

However, I optimized iteration/queries very thoroughly and we have to expect a considerable slowdown if things require e.g. an if/else or additional lookup in the "wrong" place.

But it is definitely worth thinking about how to overcome this limitation!


Regarding your high number of components... I assume you are aware of the fact that a component can contain more than a single (state) variable? Also for best iteration performance, variables that are (mostly) used together should be in the same component.

**Comment by mlange-42** [comment]
> Or should I just add them all to an exchange or something?

Missed that... Yeah, `generic.Exchange` has a `NewEntity` method. However, there is currently no `NewBatch` method like in `MapX` for fast mass-creation of entities. And (generic) `NewBatchQ` is not possible.

Would adding `Exchange.NewBatch` be helpful for the ergonomics in your use case, compared to the ID-based approach described above?

**Comment by mlange-42** [comment]
@ImVexed FYI: The component limit in the generic API was extended from 8 to 12 in #324.
